[package]
name = "wlist"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
rusqlite = { version = "0.38.0", features = ["bundled"] }
shellexpand = "3.1.1"
url_path = "0.1.3"
wlitem = "0.1.0"
